sudo: required 
service:
        - docker

before_install:
        - docker build -t kanishka300/docker-react -f Dockerfile.dev . 

script:
        - docker run -e CI=true kanishka300/docker-react npm run test -- --coverage
